all:
# Do nothing - python code is not compiled

clean:
# Do nothing - since python code is not compiled, there are no intermediate files to delete

run:
# The imu.sh script must be run as sudo, since accessing the VMXPI HAL
# requires root access.
	sudo ./imu.sh