all:
# The java compiler must have the classpath to the WPI Libraries
	gradle build

clean:
	gradle clean

run:
# To access vmxpi hardware, the application must run as sudo to have sufficient privileges
	sudo gradle run
